### ISSUE TITLE
Check on ZocDoc

### ISSUE THREAD

**Issue by ericnograles** [ericnograles/react-native-exact-target#15]
@jin-hwang-zocdoc @daniel-deutsch-zocdoc just checking on y'all and making sure everything is working fine for you?  

I'm updating docs and the Example App today to be up to snuff to RN 0.51+, may just cut a patch release for documentation updates.

**Comment by ericnograles** [comment]
FYI, pushed out a minor patch release (`0.3.1`). I noticed we were having iOS build breaks with RN 0.48+ and it was the priority of imports: https://github.com/ericnograles/react-native-exact-target/commit/b3df60638243a1b8a80142cda2ec5bdf862b20a2

**Comment by daniel-deutsch-zocdoc** [comment]
Hey @ericnograles, things are working good for us but we've actually shifted priorities a bit and probably won't need to touch the library for awhile.  If anything does come up in the future we definitely will make sure to push it back here!

**Comment by ericnograles** [comment]
Sounds good, @daniel-deutsch-zocdoc!

I'm planning an `0.4.x` release in the coming weeks to get the JB4ASDK up to speed with the current version and also exposing things around Inboxes, just FYI.
